export const LESSONS = [
  {
    id: "pwd",
    title: "現在地を知る",
    command: "pwd",
    description: "いま自分がいるフォルダの場所を表示します。",
    task: "pwd と入力して、現在地を確認しましょう。",
    hints: ["コマンドは半角で入力します。", "入力するのは pwd の3文字です。", "そのまま pwd と入力して Enter を押します。"],
    explanation: "pwd は “print working directory” の略。迷ったときに現在地を確認できます。",
    detail: "画面に /home/student と表示されれば成功です。",
    check: ({ input, result }) => input.trim() === "pwd" && result.ok,
  },
  {
    id: "ls",
    title: "中身を表示する",
    command: "ls",
    description: "現在のフォルダにあるファイルやフォルダを一覧で表示します。",
    task: "ls と入力して、ここにあるものを確認しましょう。",
    hints: ["一覧を見るコマンドです。", "小文字の l と s を使います。", "ls と入力して Enter を押します。"],
    explanation: "ls を使うと、次に開けるフォルダや読めるファイルを確認できます。",
    detail: "README.txt などのファイルと、projects/ などのフォルダが表示されました。",
    check: ({ input, result }) => input.trim() === "ls" && result.ok,
  },
  {
    id: "cd",
    title: "フォルダを移動する",
    command: "cd",
    description: "作業するフォルダを切り替えます。",
    task: "projects フォルダへ移動しましょう。",
    hints: ["移動には cd を使います。", "コマンドの後ろに移動先を続けます。", "cd projects と入力します。"],
    explanation: "cd は “change directory” の略。プロジェクトごとに作業場所を切り替えられます。",
    detail: "現在地が /home/student/projects に変わりました。",
    check: ({ state }) => state.cwd === "/home/student/projects",
  },
  {
    id: "mkdir",
    title: "フォルダを作る",
    command: "mkdir",
    description: "新しいフォルダを作成します。",
    task: "sandbox という練習用フォルダを作りましょう。",
    hints: ["フォルダ作成には mkdir を使います。", "後ろに作りたい名前を続けます。", "mkdir sandbox と入力します。"],
    explanation: "mkdir は “make directory” の略。新しい作業場所を作るコマンドです。",
    detail: "projects の中に sandbox/ が追加されました。",
    check: ({ state }) => state.directories.includes("/home/student/projects/sandbox"),
  },
  {
    id: "touch",
    title: "ファイルに触れる",
    command: "touch",
    description: "空のファイルを新しく用意します。",
    task: "memo.txt というファイルを作りましょう。",
    hints: ["ファイル作成には touch を使います。", "後ろにファイル名を続けます。", "touch memo.txt と入力します。"],
    explanation: "touch は空のファイルをすばやく用意できます。コードの土台作りにも使われます。",
    detail: "projects の中に memo.txt が追加されました。",
    check: ({ state }) => Object.hasOwn(state.files, "/home/student/projects/memo.txt"),
  },
  {
    id: "cat",
    title: "ファイルを読む",
    command: "cat",
    description: "ファイルの内容をターミナルに表示します。",
    task: "guide.txt の内容を読んでみましょう。",
    hints: ["内容表示には cat を使います。", "後ろに読みたいファイル名を続けます。", "cat guide.txt と入力します。"],
    explanation: "cat を使うと、短いテキストファイルをターミナル上ですぐ確認できます。",
    detail: "guide.txt のメッセージが表示されました。",
    check: ({ input, result }) => input.trim() === "cat guide.txt" && result.ok,
  },
];

export const ROUTES = [
  {
    id: "ai", title: "AIでコードを書く", description: "AIツールを使って開発を効率化しよう", label: "おすすめ", tone: "green",
    purpose: "AIに頼む前に、作業場所を分ける習慣を身につけます。",
    firstStep: "AIとの練習専用フォルダを1つ作る",
    command: "mkdir ai-playground",
  },
  {
    id: "git", title: "Gitを使いこなす", description: "バージョン管理で開発をもっと安全に", label: "人気", tone: "purple",
    purpose: "変更履歴を管理するプロジェクトの置き場所を準備します。",
    firstStep: "バージョン管理するフォルダを1つ作る",
    command: "mkdir versioned-project",
  },
  {
    id: "node", title: "Node.jsで動かす", description: "JavaScriptで小さなアプリを動かそう", label: "定番", tone: "blue",
    purpose: "Node.jsで最初に動かすJavaScriptファイルを用意します。",
    firstStep: "アプリの入口になるファイルを1つ作る",
    command: "touch app.js",
  },
];
